### ISSUE TITLE
Game name vs. repo name

### ISSUE THREAD

**Issue by jbeich** [fishfight/jumpy#406]
https://github.com/fishfight/FishFight was renamed to https://github.com/fishfight/jumpy but there's no reference to `jumpy` in the source code yet, so the main executable is still `fishfight`. [Noticed downstream](http://www.ipv6proxy.net/go.php?u=http://beefy5.nyi.freebsd.org/data/122i386-default/fa63d4de0a02/logs/errors/fishfight-0.4.2_1.log) due to top directory changing checksum of [v0.4.2 tarball](https://github.com/fishfight/jumpy/archive/refs/tags/v0.4.2.tar.gz).

Related to https://twitter.com/fishfightgame/status/1506394504726822916 
> (Formerly known as just Fish Fight, as it was the first game in what later became a series of games.

**Comment by jbeich** [comment]
If not clear, this is about https://github.com/fishfight/FishFight redirecting to https://github.com/fishfight/jumpy

**Comment by jbeich** [comment]
According to https://twitter.com/fishfightgame/status/1506394504726822916 the rename seems to be intentional:
> (Formerly known as just Fish Fight, as it was the first game in what later became a series of games.

For this issue to be fixed the references in the code need to be adjusted.

**Comment by erlend-sh** [comment]
Ah yeh that’s my bad, thanks for reporting. I should’ve expected the rename to break some things. We’ll fix it.

**Comment by erlend-sh** [comment]
Reverted back for now. This issue will close once we’ve renamed the repo to ‘jumpy’, in line with the other games in the Fish Fight series.
